name: Deploy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Start services with Docker Compose
        run: docker compose up -d

      - name: Wait for services to be available
        run: sleep 15

      - name: Execute migrations with Flyway
        working-directory: backend
        run: ./gradlew flywayMigrate

      - name: Execute Spring Boot tests
        working-directory: backend
        run: ./gradlew test

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Execute Vitest tests
        working-directory: frontend
        run: npm run test
